a = int(input("Enter The Number: "))
b = int(input("Enter The Second Number: "))

c = input("Enter The Operation: ")

if c == "+" :
   print("The Sum Og Two Number's Is: ", a + b);

elif(c == "-"):
   print("The Subtraction Of Two Number Is: ", a - b)

elif(c == "*"):
   print("The Multiplication Of Two Number's Is: ", a * b)

elif (c == "/"):
   print("The Division Of Two Number Is: ", a / b)